version: "3.8"
services:
 pushservice:
  build: pushservice
  container_name: pushservice
 smsservice:
  build: smsservice
  container_name: smsservice
 emailservice:
  build: emailservice
  container_name: emailservice
 eureka:
  build: eureka
  container_name: eureka
  ports: 
   - 8761:8761
 gateway:
  build: gateway
  container_name: gateway
  ports: 
   - 8080:8080
 mongodb:
  image : mongo
  container_name: mongodb
  environment:
   - PUID=1000
   - PGID=1000
  restart: unless-stopped