#Eureka/port Config below is used for running locally
server:
  port: 8080

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
#Gateway configuration
spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: push-notification
          uri: lb://PUSH-NOTIFICATION
          predicates:
            - Path=/push/**
        - id: email-notification
          uri: lb://EMAIL-NOTIFICATION
          predicates:
            - Path=/email/**
        - id: sms-notification
          uri: lb://SMS-NOTIFICATION
          predicates:
            - Path=/sms/**